name: Pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ DATABASE_URL }}
      POSTGRES_USER: ${{ POSTGRES_USER }}
      POSTGRES_DB: ${{ POSTGRES_DB }}
      POSTGRES_PASSWORD: ${{ POSTGRES_PASSWORD }}
      SECRET_KEY: ${{ SECRET_KEY }}
      ALGORITHM: ${{ ALGORITHM }}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${{ ACCESS_TOKEN_EXPIRE_MINUTES }}

    steps:
      - name: Copiar arquivos
        uses: actions/checkout@v4

      - name: Instalar o python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Instalar o poetry
        run: pipx install poetry
      
      - name: Instalar dependÃªncias
        run: poetry install

      - name: Executar testes
        run: poetry run task test
